logging:
  path: logs/clongulinconsumer/
  level:
    org:
      springframework:
        data: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'


server:
  port: 8082

HOST_NAME: localhost
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${HOST_NAME}:${server.port}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    # 和git里的文件名对应
    name: clongulinconsumer

